server:
  address: ":8199"
  serverTimeout: 300s
  clientMaxBodySize: 104857600
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level: "all"
  stdout: true

database:
  default:
    link: "mysql:root:Test@123456@tcp(fabric-sdk-mysql:3306)/esg?charset=utf8mb4&parseTime=True&loc=Local"
    debug: true

redis:
  default:
    address: 127.0.0.1:6379
    db: 1
