---
name: test-network-fixed-trust
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
      orderer: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
-----BEGIN CERTIFICATE-----
MIICVzCCAf2gAwIBAgIQea5aDykeepLNVWxS2i2n0zAKBggqhkjOPQQDAjB2MQsw
CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
Y2Eub3JnMS5leGFtcGxlLmNvbTAeFw0yNTA3MTcxMDQzMDBaFw0zNTA3MTUxMDQz
MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMR8wHQYD
VQQDExZ0bHNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
AQcDQgAE+56Xl9tMVTe5yCsPxldVgJdBzuxoh/JXSD5VspoVXqGKnlZ8ZlH4/pax
RmjyL1Z45bxkQkCJB7vGpwvh3yYym6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
DgQiBCCYUJinbLe2/ydSKdkzUuF4a6aZRCgguR9nSNMbyChJOzAKBggqhkjOPQQD
AgNIADBFAiEAmAkXTD7MfC8jpVO49nHesEbzzntB3VxUJnC13VpxYg8CIBsRwRA3
Ic53jttFfENNNMw/NQ7bRWcETj0sGRC7jZRz
-----END CERTIFICATE-----
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      allow-insecure: false
orderers:
  orderer.example.com:
    url: grpcs://localhost:7050
    tlsCACerts:
      pem: |
-----BEGIN CERTIFICATE-----
MIICQzCCAeqgAwIBAgIRAPFgl7QPzFoT4/fxu7zyP5YwCgYIKoZIzj0EAwIwbDEL
MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
cmFuY2lzY28xFDASBgNVBAoTC2V4YW1wbGUuY29tMRowGAYDVQQDExF0bHNjYS5l
eGFtcGxlLmNvbTAeFw0yNTA3MTcxMDQzMDBaFw0zNTA3MTUxMDQzMDBaMGwxCzAJ
BgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJh
bmNpc2NvMRQwEgYDVQQKEwtleGFtcGxlLmNvbTEaMBgGA1UEAxMRdGxzY2EuZXhh
bXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASXfUCZOCS+ysXeDdzl
rNbbVFr8H662be3smUrkkeaDYT/JYQyvmoDv9uIG/NwrVK0Z0CCWuj1BTwfy+Zev
xi8Eo20wazAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsG
AQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0OBCIEIKhgUc3RH0/tQyt+yZfj
5eG5lKkFFbh9ciXLUkQGnUDPMAoGCCqGSM49BAMCA0cAMEQCID4wkLi+fEopAaGy
lIK5OpqYRAuY+GJVOaCAuonQ5J7BAiA2EcP+0JYyIBxDFH5xBg66bJ/Y5of0bgek
ZG55B/pvLA==
-----END CERTIFICATE-----
    grpcOptions:
      ssl-target-name-override: orderer.example.com
      allow-insecure: false
channels:
  mychannel:
    orderers:
      - orderer.example.com
    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true