name: "test-network-org1"
version: 1.0.0

client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com

peers:
  peer0.org1.example.com:
    url: grpc://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
      allow-insecure: true
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICVzCCAf2gAwIBAgIQea5aDykeepLNVWxS2i2n0zAKBggqhkjOPQQDAjB2MQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
        Y2Eub3JnMS5leGFtcGxlLmNvbTAeFw0yNTA3MTcxMDQzMDBaFw0zNTA3MTUxMDQz
        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMR8wHQYD
        VQQDExZ0bHNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
        AQcDQgAE+56Xl9tMVTe5yCsPxldVgJdBzuxoh/JXSD5VspoVXqGKnlZ8ZlH4/pax
        RmjyL1Z45bxkQkCJB7vGpwvh3yYym6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
        DgQiBCCYUJinbLe2/ydSKdkzUuF4a6aZRCgguR9nSNMbyChJOzAKBggqhkjOPQQD
        AgNIADBFAiEAmAkXTD7MfC8jpVO49nHesEbzzntB3VxUJnC13VpxYg8CIBsRwRA3
        Ic53jttFfENNNMw/NQ7bRWcETj0sGRC7jZRz
        -----END CERTIFICATE-----

certificateAuthorities:
  ca.org1.example.com:
    url: http://localhost:7054
    caName: ca-org1
    httpOptions:
      verify: false
    tlsCACerts:
      pem:
        - |
          -----BEGIN CERTIFICATE-----
          MIICUjCCAfigAwIBAgIRAJ+sUuzFqOFICdYEZil8+4EwCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjUwNzE3MTA0MzAwWhcNMzUwNzE1MTA0MzAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BIcgnz/2e7r1QypPK9RcVLa24NjsOukYbY9tvRivZW4kgMObnPdwNKDXe0v3eSMP
          umUY97rBNcxO/x0XCKWbQayjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          C00VUtNAfjaSHc95WBQ3d40Nt8uQFPQCt3ZVka2QpzowCgYIKoZIzj0EAwIDSAAw
          RQIhAJLhrPxod+6s//lLiqQKGuodjsXEgtsDqBT0iTzn6oQfAiAjaQ/wunThClj+
          C7as7s+TP6tsFTLkZxStDSB6157V+g==
          -----END CERTIFICATE----- 